### ISSUE TITLE
Hour is not correct

### ISSUE THREAD

**Issue by fchauveau** [fchauveau/rpi-domoticz-docker#3]
Hi @MichaelBitard 

We need to make docker using same hour than host as many things can be parametrized based on hour.

**Comment by MichaelBitard** [comment]
https://github.com/docker/docker/issues/12084#issuecomment-89697533

You can add 

```
-v /etc/localtime:/etc/localtime
```

and it should work

**Comment by fchauveau** [comment]
Hmmm, if its the best way to do it, its okay to me
