### ISSUE TITLE
getting PI internal sensor data

### ISSUE THREAD

**Issue by aikomastboom** [fchauveau/rpi-domoticz-docker#4]
I had to add the following parameters to the `docker run` command to make the Hardware (Motherboard sensors) work

 `--device=/dev/vchiq -e LD_LIBRARY_PATH=/opt/vc/lib -v /opt/vc:/opt/vc:ro`

The command that needs to work inside the container is: `/opt/vc/bin/vcgencmd measure_temp`
( from: https://github.com/domoticz/domoticz/search?utf8=✓&q=szInternalTemperatureCommand )

**Comment by MichaelBitard** [comment]
Thanks for that, I'll add it to the README.

**Comment by hh2015** [comment]
This is really great help. Despite the information above I was not able to change my 
`docker-compose.yml` accordingly to run the container properly in this way.
I was in the assumption that I need just to add the volume, device and environment varible there. But obviously `/opt/vc/bin/vcgencmd measure_temp` is still not executed in my case.

Below I show you the relevant part of my`docker-compose.yml`. I would appreciate if you could find the issue. I guess this is interessting for all other using docker compose
`version: '2`
`services:`
`  portainer:`
`    container_name: portainer`
`    image: portainer/portainer`
`    restart: unless-stopped`
`    ports:`
`      - 9000:9000`
`    volumes:`
`      - /var/run/docker.sock:/var/run/docker.sock`
`      - ./volumes/portainer/data:/data`
`  nodered:`
`    container_name: nodered`
`    build: ./services/nodered/.`
`    restart: unless-stopped`
`    user: "0"`
`    ports:`
`      - 1880:1880`
`    volumes:`
`      - ./volumes/nodered/data:/data`
**`      - /opt/vc:/opt/vc:ro`**
**`    devices:`**
**`      - "/dev/vchiq:/dev/vchiq"`**
**`    environment:`**
**`      - LD_LIBRARY_PATH=/opt/vc/lib`**

**Comment by MichaelBitard** [comment]
I'm sorry, this is not related at all to domoticz right? This is related to the nodered image you are using
