### ISSUE TITLE
Domoticz version 3.5837 released

### ISSUE THREAD

**Issue by aikomastboom** [fchauveau/rpi-domoticz-docker#5]
https://www.domoticz.com/forum/viewtopic.php?f=3&t=13942&sid=ee1ca6b222996de2b7c619aa5373c230

**Comment by MichaelBitard** [comment]
I'm building it

**Comment by aikomastboom** [comment]
:thumbs_up:

**Comment by MichaelBitard** [comment]
tag 3.5837 pushed, you can use the image from agileek/rpi-domoticz-docker:3.5837

Tested at home and everythings seems to work

**Comment by MichaelBitard** [comment]
Correction, the docker image is still uploading, should be good in ~10 minutes

**Comment by fchauveau** [comment]
:+1: well done @MichaelBitard working perfectly
